### ISSUE TITLE
Annoying scrollbar

### ISSUE THREAD

**Issue by TheJaredWilcurt** [Antrikshy/Quibbler#4]
I keep getting a scrollbar appearing at the bottom of the screen and then disappearing. Since this is where the input field is pinned, it's where I'm trying to type and thus it bouncing up and down constantly is super annoying.

Why not just do an `overflow: hidden` on whatever element is being pushed around.

Testing in Chrome Canaray, Win 7, 1920x1080.

**Comment by FoxxMD** [comment]
+1 Experiencing this as well

**Comment by Antrikshy** [comment]
I'm trying to apply this to the message element and to the visualizer itself. Doesn't seem to work. I'll try to fiddle around with this. If anyone manages to fix it, send a PR!

**Comment by Antrikshy** [comment]
A friend just fixed it. I didn't realize how annoying it was on Windows.
