### ISSUE TITLE
I really don't like whole the tag concept

### ISSUE THREAD

**Issue by faissaloo** [Antrikshy/Quibbler#8]
I think the whole fun with quibbler was the fact that every message you posted was anonymous, adding tags kinda messes with that and I would prefer if they weren't there.

**Comment by Antrikshy** [comment]
There was a huge push for it, so I added them. They are completely optional. You can go tag less. They only make it easier to track conversations and people were copy-pasting their tags anyway. There is still no login system and tags are not persistent anywhere.
